### ISSUE TITLE
incompatability with 1.6.0.2

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Illuminati-Companion#2]
Hi,
There is a compatibility issue with the companion with 1.6.0.2. Unfortunately i don't have the python log error in front of me, but it can be easily reproduced by playing a random battle. You will notice that when a player is killed, the killfeed won't display, nor will the player panel update.

**Comment by Aimdrol** [comment]
Has been fixed with a80778c9c357c9704de68451ed54f82d60d44caa
It also occurred in MLG-Main and MLG-RTAN. It has been fixed there as well. 

As always: thanks for helping me find and fix issues with the mod
